Iter13
alxrusinov/shorturl pull request #13
Opened 2024-08-13 11:32 UTC by alxrusinov

2024-08-14 07:56 UTC, tmvrus requested changes
К сожалению в работе никак не затронута работы с контекстами, а это первая часть спринта.

2024-08-14 07:56 UTC, tmvrus commented on internal/store/dbStore.go
> +func (store *DBStore) SetBatchLink(arg []*StoreArgs) ([]*StoreArgs, error) {
передавать слайс по ссылке нет большого смысла, это и так уже ссылочный тип

2024-08-14 07:56 UTC, tmvrus commented on internal/handler/handler.go
> +		dbErr.Err = err
а зачем так делать? `errors.As` и так заполнит это полез из оригинальной ошибки
https://play.golang.com/p/BAMfAs7H8eD

2024-08-14 09:17 UTC, alxrusinov commented on internal/store/dbStore.go
> +func (store *DBStore) SetBatchLink(arg []*StoreArgs) ([]*StoreArgs, error) {
здесь используется  слайс ссылок для совместимости с обработчиком и функциями-хэлперами. Позволяет перед передачей слайса в стор избежать дополнительных циклов создания промежуточных слайсов структур. Упрощает логику обработки, особенно для файлового хранилища

2024-08-15 11:33 UTC, tmvrus commented on internal/store/dbStore.go
> +func (store *DBStore) SetBatchLink(arg []*StoreArgs) ([]*StoreArgs, error) {
Промежуточный структуры создаются на стеке ф-и и уничтожаются сразу после ее завершения, нагрузка на сборку мусора при этом отсутствует, чего нельзя утверждать при передаче указателя.

2024-08-15 11:35 UTC, tmvrus requested changes
Полностью проигнорировано замечание относительно использования контекстов

2024-08-15 11:45 UTC, alxrusinov commented
Можно разъяснить, что конкретно должно быть сделано в плане работы с контекстом. В описании инкрементов нет конкретных требований завершения запросов по таймеру или передачи значений.
В правках запросы к базе переведены на запросы с контекстом, например err := `stmt.QueryRowContext(context.Background(), val.ShortLink, val.OriginalLink, val.CorrelationID).Scan(&res.ShortLink, &res.OriginalLink, &res.CorrelationID)`

2024-08-21 04:09 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью второго спринта! 🎉 В этом спринте наше приложение стало еще сложнее, добавился новый слой БД 💪 Ты реализовал доработки сервиса в соответствии с постановкой задачи. Отличная работа! 🚀 Тем не менее, мне хотелось бы добавить несколько комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Код функционален и корректен! 🚀
2. Ты консистентно встроил функционал в структуру существующего приложения. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Стоит добавить тесты для нового эндпоинта.
2. Стоит добавить обработку конфликтов в инмемори хринилище.
3. Было бы здорово увидеть реализацию управления жизненным циклом приложения при помощи контекста.

2024-08-21 04:09 UTC, vokinneberg commented on internal/handler/handler.go
> +	res, err := handler.store.SetLink(links)
Я понимаю, что происходит, когда мы пытаемся сократить URL, уже имеющийся в базе. В этом случае ты возвращаешь и результат, и ошибку. Это не совсем стандартный подход, и я бы не рекомендовал так делать. Обычно, если мы получили ошибку, нет необходимости проверять результат — это стандартное поведение. Если хочется вернуть существующий URL вместе с ошибкой, можно сделать ещё один запрос к  store - это позволит оставаться методам store более "чистыми" и логику сделает более наглядной.

2024-08-21 04:09 UTC, vokinneberg commented on internal/handler/handler.go
> +		if !errors.As(err, &dbErr) {
Я бы советовал использовать однострочную проверку вместо сложенных if.
```suggestion
	if err != nil && !errors.As(err, &dbErr) {
```

2024-08-21 04:09 UTC, vokinneberg commented on internal/handler/handler.go
> +	if err := json.NewDecoder(ctx.Request.Body).Decode(&content); err != nil && !errors.Is(err, io.EOF) {
А если ошибка `io.EOF` нам не нужно ее обрабатывать? Так же мне кажется, что если мы не смогли спарсить `body` более корректно вернуть `400 BadRequest` это даст пользователю больше информации о том, что произошло.

2024-08-21 04:09 UTC, vokinneberg commented on internal/handler/handler.go
> +		ctx.AbortWithStatus(http.StatusNotFound)
Мне кажется в этом случае это должна быть `StatusInternalServerError`, так как URL возможно и был найден, но что-то еще пошло не так.

2024-08-21 04:09 UTC, vokinneberg commented on internal/store/dbStore.go
> +func (store *DBStore) SetBatchLink(arg []*StoreArgs) ([]*StoreArgs, error) {
Соглашусь с Мишей, в данном случае не увидел какого-то упрощения. Слайс передается по ссылке и копирования структур не произойдет, так что в этом смысле такая техника избыточна. При этом при енумерации списка не получится, например без проверки на `nil` обращаться к полям структуры.
Если можно, поясни подробнее, что ты имеешь ввиду под _дополнительных циклов создания промежуточных слайсов структур_?

2024-08-21 04:09 UTC, vokinneberg commented on internal/handler/handler_test.go
> +	testHandler.store.SetLink(links)
Стоит добавить тесты для нового эндпоинта.

2024-08-21 04:09 UTC, vokinneberg commented on internal/store/FileStore.go
> +			return arg, &DuplicateValueError{Err: errors.New("record already exists")}
👍 за реализацию обратной совместимости!

2024-08-21 04:09 UTC, vokinneberg commented on internal/store/FileStore.go
> +	newUUID := uuid.NewString()
Можно вынести дублирующийся код в `SetLink(...)` и `SetBatchLink(...)` в отдельный метод.

2024-08-21 04:09 UTC, vokinneberg commented on internal/store/dbStore.go
> +	initialQuery := `CREATE TABLE IF NOT EXISTS links (
Так как у нас поиск происходит по полю `short` было бы полезно добавить индекс на это поле.

2024-08-21 04:09 UTC, vokinneberg commented on internal/store/dbStore.go
> +		log.Fatal(err)
Не стоит вызывать `log.Fatal(err)` где-либо в приложении кроме метода `mail`. Этот вызов приведет к немедленному выходу из приложения, чего мы вряд ли хотим даже в случае если произошла ошибка. Думаю стоит обработать и вернуть ошибку в вызывающий код.

2024-08-21 04:09 UTC, vokinneberg commented on internal/store/inMemoryStore.go
> +	store.data[arg.ShortLink] = arg
Почему-то не реализовали обработку дубликатов в этом хранилище?

2024-08-24 17:02 UTC, merged